# Generated by Django 4.2.7 on 2023-11-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WriterBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("writer", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ข้อมูลบทความ",
                "verbose_name_plural": "ข้อมูลบทความ",
            },
        ),
    ]
