# Generated by Django 4.2.7 on 2023-11-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writerblog',
            options={'verbose_name': 'ข้อมูลบทความ', 'verbose_name_plural': 'ข้อมูลบทความ'},
        ),
    ]
