# Generated by Django 4.2.7 on 2023-11-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WriterBlog",
            new_name="Blog",
        ),
    ]
