# Generated by Django 5.0 on 2023-12-11 08:15

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blog_bookmark_article"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="blog",
            managers=[
                ("newmanager", django.db.models.manager.Manager()),
            ],
        ),
    ]
