# Generated by Django 5.0 on 2023-12-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="blog",
            managers=[],
        ),
    ]
