# Generated by Django 5.0 on 2023-12-29 07:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blog_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
