# Generated by Django 5.0 on 2023-12-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_birthday_alter_customuser_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_img",
            field=models.FileField(upload_to=""),
        ),
    ]
