# Generated by Django 5.0 on 2023-12-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_birthday_customuser_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
